
<h1>Agregar Tarea</h1>

<form action="index.php?action=store" method="post">
    <label for="title">Título:</label>
    <input type="text" id="title" name="title" required><br>

    <label for="description">Descripción:</label>
    <textarea id="description" name="description" required></textarea><br>

    <input type="submit" value="Guardar">
</form>

<a href="index.php?action=index">Volver a la lista</a>
