<!DOCTYPE html>
<html>
<head>
    <title>Crear Tarea</title>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet" >
</head>
<body class="bg-gray-100">
    <div class="container mx-auto p-4 mt-8">
        <h1 class="text-2xl font-bold mb-4">Crear Tarea</h1>

        <form method="post" action="" class="mb-4">
            <input type="hidden" name="action" value="create">
            <div class="mb-4">
                <label for="title" class="block text-sm font-medium text-gray-700">Título:</label>
                <input type="text" name="title" required class="border rounded py-2 px-3 focus:outline-none focus:border-blue-400 w-full">
            </div>
            <div class="mb-4">
                <label for="user" class="block text-sm font-medium text-gray-700">Usuario:</label>
                <input type="text" name="user" required class="border rounded py-2 px-3 focus:outline-none focus:border-blue-400 w-full">
            </div>
            <div class="mb-4">
                <label for="description" class="block text-sm font-medium text-gray-700">Descripción:</label>
                <input type="text" name="description" required class="border rounded py-2 px-3 focus:outline-none focus:border-blue-400 w-full">
            </div>
            <div class="mb-4">
                <label for="starTime" class="block text-sm font-medium text-gray-700">Inicio:</label>
                <input type="datetime-local" name="starTime" required class="border rounded py-2 px-3 focus:outline-none focus:border-blue-400 w-full">
            </div>
            <div class="mb-4">
                <label for="endTime" class="block text-sm font-medium text-gray-700">Final:</label>
                <input type="datetime-local" name="endTime" required class="border rounded py-2 px-3 focus:outline-none focus:border-blue-400 w-full">
            </div>
            <div class="mb-4">
                <label for="status" class="block text-sm font-medium text-gray-700">Estado:</label>
                <select name="status" required class="border rounded py-2 px-3 focus:outline-none focus:border-blue-400 w-full">
                    <option value="Pending">Pendiente</option>
                    <option value="Running">En Progreso</option>
                    <option value="Completed">Completada</option>
                </select>
            </div>
            <button type="submit" class="bg-green-500 text-white py-2 px-4 rounded hover:bg-green-600 focus:outline-none focus:bg-green-600">Agregar Tarea</button>
            <a href="index.php" class="bg-blue-500 text-white py-2 px-4 rounded hover:bg-blue-600 focus:outline-none focus:bg-blue-600">Volver atras</a>
        </form>
    </div>
</body>
</html>
