<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Delete!</title>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
</head>
<body class="bg-gray-100 p-8">
<div class="max-w-md mx-auto bg-white rounded p-6 shadow-lg">
    <h1 class="text-2xl font-bold mb-4">La tarea a sido borrada</h1>
    <form method="post" action="showTasks.php">
        <a href="showTasks.php" class="btn-cancel text-white bg-green-500 hover:bg-grenn-600 py-2 px-4 rounded transition duration-300 ease-in-out">Lista de tareas</a>
        <a href="index.php" class="btn-confirm text-white bg-blue-500 hover:bg-blue-600 py-2 px-4 rounded transition duration-300 ease-in-out">Home</a>
    </form>
</div>
</body>
</html>
