<!DOCTYPE html>
<html>
<head>
    <title>Gestor de Tareas</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css">
</head>
<body class="bg-gray-100 h-screen flex items-center justify-center">
    <div class="bg-white rounded-lg shadow-md p-8 max-w-md w-full">
        <h1 class="text-2xl font-semibold mb-4 text-center">Gestor de Tareas</h1>

        <a href="createTask.php" class="bg-green-500 text-white px-4 py-2 rounded-lg block mb-4 hover:bg-green-600 transition duration-200 ease-in-out text-center">Crear Nueva Tarea</a>
        <a href="showTasks.php" class="bg-blue-500 text-white px-4 py-2 rounded-lg block hover:bg-blue-600 transition duration-200 ease-in-out text-center">Ver Lista de Tareas</a>
    </div>
</body>
</html>
